---
version: "3"
services:
 z-ubuntu:
  image: z-ubuntu
  networks:
   - z-net
 z-postgres:
  image: z-postgres
  networks:
   - z-net
  ports:
   - 5432:5432
  env_file:
   - Env/postgres-variables.env
  volumes:
   - project-z-pgdata:/var/lib/postgresql/data
 z-pgadmin:
  image: z-pgadmin
  networks:
   - z-net
  ports:
   - 8003:80
  env_file:
   - Env/pgadmin-variables.env
  volumes:
   - project-z-pgadmin:/var/lib/pgadmin
 z-nginx:
  image: z-nginx
  networks:
   - z-net
  ports:
   - 80:80
networks:
 z-net:
  driver: bridge
volumes:
 project-z-pgdata:
  driver: local
 project-z-pgadmin:
  driver: local
