---
version: "3"
services:
 z-postgres:
  image: postgres
  ports:
   - 5432:5432
  env_file:
   - postgres-variables.env
  volumes:
   - project-z-pgdata:/var/lib/postgresql/data
 z-pgadmin:
  image: dpage/pgadmin4
  ports:
   - 8003:80
  env_file:
   - pgadmin-variables.env
  volumes:
   - project-z-pgadmin:/var/lib/pgadmin
 z-nginx:
  image: z-nginx
  ports:
   - 80:80
volumes:
 project-z-pgdata:
  driver: local
 project-z-pgadmin:
  driver: local
