---
version: "3"
services:
  y-pgadmin:
    build: ./Y-Images/Y-Pgadmin
    image: y-pgadmin
    networks:
      - y-net
    ports:
      - 8003:80
    env_file:
      - Env/pgadmin-variables.env
    volumes:
      - project-y-pgadmin:/var/lib/pgadmin
networks:
  y-net:
    external:
      name: y-net
volumes:
  project-y-pgadmin:
    driver: local
