---
version: "3"
services:
  y-postgres:
    build: ../Y-Images/Y-Postgres
    image: y-postgres
    networks:
      - y-net
    ports:
      - 5432:5432
    env_file:
      - ../Env/postgres-variables.env
    volumes:
      - project-y-pgdata:/var/lib/postgresql/data
  y-pgadmin:
    build: ../Y-Images/Y-Pgadmin
    image: y-pgadmin
    networks:
      - y-net
    ports:
      - 8003:80
    env_file:
      - ../Env/pgadmin-variables.env
    volumes:
      - project-y-pgadmin:/var/lib/pgadmin
networks:
  y-net:
    external:
      name: y-net
volumes:
  project-y-pgdata:
    driver: local
  project-y-pgadmin:
    driver: local
